---
title: Cloud4est - Community
timezone: Europe/Budapest
collections:
  authors:
    title: Authors
    output: true
    permalink: "/authors/:path/"
  langs:
    title: Langs
    output: false
  pages:
    title: Navbar
    output: true
  posts:
    title: Posts
    output: true
  styles:
    title: Styles
    output: false
  topics:
    title: Topics
    output: true
    permalink: "/topics/:path/"
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: default
    image: https://picsum.photos/1920/1080
    author: Szerző
    lang: hu
    style: bottom
    is-featured: true
    topic: történetek
- scope:
    path: ''
    type: authors
  values:
    layout: flowing
    type: author
- scope:
    path: ''
    type: topics
  values:
    layout: flowing
    type: topic
- scope:
    path: _pages
  values:
    layout: default
description: Cloud4est - Community website
email: youremailaddress@gmail.com
plugins:
- jekyll-seo-tag
- jekyll-sitemap
logo: "/assets/images/CD4ST_logo.svg"
social:
  links:
  - https://www.facebook.com/CD4ST
  - https://twitter.com/CD4ST
  - https://www.instagram.com/cloud4st/
  - https://www.youtube.com/channel/UC1aBUmUZTGBWwj5N9ktfx7w
  - https://github.com/Cloud4est/
baseurl: "/site_community"
permalink: pretty
url: https://cloud4est.github.io
pic: "/images/CD4ST_logo.svg"
banner: "/images/Montage-YT_11-02.svg"
twitter_url: https://twitter.com/CD4ST/
facebook_url: https://facebook.com/CD4ST/
github_url: https://github.com/Cloud4est/
instagram_url: https://instagram.com/cloud4st/
youtube_url: https://www.youtube.com/channel/UC1aBUmUZTGBWwj5N9ktfx7w
markdown: kramdown
include:
- _pages
