---
title: Community
timezone: Europe/Budapest
collections:
  navbar:
    title: Navbar
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: youremailaddress@gmail.com
baseurl: "/site_community"
url: https://cloud4est.github.io
pic: "/images/pic01.jpg"
overlay: "/assets/css/images/overlay.png"
favicon: 
featured-image-source: 
500px_url: 
facebook_url: 
github_url: https://github.com/Cloud4est/
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url: 
slack_url: 
twitter_url: 
markdown: kramdown
include:
- _pages
