---
title: Community
timezone: Europe/Budapest
collections:
  authors:
    title: Authors
    output: true
    permalink: "/authors/:path/"
  langs:
    title: Langs
    output: false
  posts:
    title: Posts
    output: true
  styles:
    title: Styles
    output: false
  topics:
    title: Topics
    output: true
    permalink: "/topics/:path/"
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: default
- scope:
    path: ''
    type: authors
  values:
    layout: flowing
    type: author
- scope:
    path: ''
    type: topics
  values:
    layout: flowing
    type: topic
email: youremailaddress@gmail.com
baseurl:
url: https://community.cloud4est.com
pic: "/images/CD4ST_logo.svg"
banner: "/images/Montage-YT_11-02.svg"
twitter_url: https://twitter.com/CD4ST/
facebook_url: https://facebook.com/CD4ST/
github_url: https://github.com/Cloud4est/
instagram_url: https://instagram.com/cloud4st/
linkedin_url:
markdown: kramdown
include:
- _pages
