---
title: Community
timezone: Europe/Budapest
collections:
  posts:
    title: Posts
    output: true
    location: home
  uploads:
    title: Uploads
    output: true
email: youremailaddress@gmail.com
baseurl:
url: https://community.cloud4est.com
pic: "/images/CD4ST_logo.svg"
banner: "/images/banner.jpg"
twitter_url: https://twitter.com/CD4ST/
facebook_url: https://facebook.com/CD4ST/
github_url: https://github.com/Cloud4est/
instagram_url:
linkedin_url:
markdown: kramdown
include:
- _pages
